#!/usr/bin/env Rscript

# Code modified from Stephen Sefick's 2016 plotvcftable.R script
# Generated by Amanda Clark 2022 to visualize GATK site tables in R 4.0 on EASLEY HPC


# Check for command line arguments
args = commandArgs(trailingOnly=TRUE)

# Error without at least the input file argument (which should be the site table generated with GATK in visualize_vcf.sh or run_visualize_variantQuality.sh)
# test if there is at least one argument: if not, return an error
if (length(args)==0) {
  stop("At least one argument after the script is required (input file - site table from GATK).n", call.=FALSE)
} else if (length(args)==1) {
  # default output file
  args[2] = paste(gsub(" ", "_", date()), "gatk_plots.pdf", sep = "_")
}


# load packages 
# vector of packages
packs <- c("tidyverse", "grid", "gtable", "gridExtra", )
# loop through and check for package, install if not present, and load library
for (pack in packs){
if (!require(pack)) install.packages('pack')
library(pack)
}


# Read in data; this will be a command line argument that should be the site table generated with GATK in visualize_vcf.sh
x <- read_delim(args[1],  delim = "\t", col_names = T)

# Make density plots of the parameters in data highlighted by GATK as important quality metrics/statistics
## You may want to look at different cut-offs other than the GATK recommended defaults, based on your data. Edit the geom_vline to change the cut-offs
## Plots with xlim arguments are based off of my data, remove them on your first plotting/adjust them to fit your data  

RPRS.plot <- ggplot(x, aes(x=ReadPosRankSum))+ geom_density(alpha=0.2) + 
		geom_vline(xintercept = -8, colour="red") + ggtitle("ReadPosRankSum - Negative values indicate ALT near ends")

MQRS.plot <- ggplot(x, aes(x=MQRankSum))+geom_density(alpha=0.2) + 
		geom_vline(xintercept = -12.5, colour="red") + ggtitle("MQRankSum of Mapping Quality - Negative values indicate ALT near ends")

SOR.plot <- ggplot(x, aes(x=SOR))+geom_density(alpha=0.2) + 
		geom_vline(xintercept = 3, colour="red") + ggtitle("StrandOddsRatio (SOR) - Greater than 3 shows strand bias")
MQ.plot <- ggplot(x, aes(x=MQ))+geom_density(alpha=0.2) + 
		geom_vline(xintercept = 40, colour="red") + ggtitle("Root Mean Square Error Mapping Quality (MQ) - Less than 40 removed")

FS.plot <- ggplot(x, aes(x=FS))+geom_density(alpha=0.2)
if(!any(x$FS==0)){
FS.plot <- FS.plot + scale_x_log10() + geom_vline(xintercept = 60, colour="red") + ggtitle("Fisher Strand (FS- Strand Bias Variant on F or R)") + xlim(0,100)
}else{
FS.plot <- FS.plot + geom_vline(xintercept = 60, colour="red") + ggtitle("Fisher Strand (FS- Strand Bias Variant on F or R)") + xlim(0,100)

QD.plot <- ggplot(x, aes(x=QD))+geom_density(alpha=0.2) + 
		geom_vline(xintercept = 2, colour="red") + ggtitle("QD -variant qual/unfiltered depth")
QUAL.plot <- ggplot(x, aes(x=QUAL)) + 
		geom_density(alpha=0.2) + ggtitle("QUAL- Quality Metric") + xlim(0,100000)


DP.plot <- ggplot(x, aes(x=DP)) + 
		geom_density(alpha=0.2) + ggtitle("DP- Depth") + xlim(0,1500)

# Getting 5*SD from mean; will use to make another plot and the table at the end for depth filtering suggestions  
x_bar<- mean(x$DP, na.rm=TRUE)
SD <- sd(x$DP, na.rm=TRUE)
x_bar_SD <- x_bar + (5*SD)
stats <- data.frame(mean=x_bar, SD=SD, mean_plus_5xSD=x_bar_SD)
t1 <- tableGrob(stats)
title <- textGrob("Depth Statistics",gp=gpar(fontsize=50))
padding <- unit(5,"mm")
table <- gtable_add_rows(t1, heights = grobHeight(title) + padding, pos = 0)
table <- gtable_add_grob(table, title, 1, 1, 1, ncol(table))

# use this code to make the filtered plot suggested by the table above
#DP.plot <- DP.plot + geom_vline(xintercept=x_bar_SD, col="red")+xlim(0, x_bar_SD+50)


pdf(args[2])
FS.plot
QD.plot
RPRS.plot
MQRS.plot
SOR.plot
MQ.plot
QUAL.plot
DP.plot
grid.newpage()
grid.draw(table)
dev.off()
